management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /manage
  metrics:
    enable:
      process: false
      jdbc: false
      logback: false
      spring: false
      tomcat: false
      hikaricp: false
    use-global-registry: false
    export:
      cloudwatch:
        namespace: Micrometer/test
        enabled: true
        batch-size: 20
        step: 1s
cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1
aws:
  ec2:
    meta-data-url: http://169.254.169.254/latest/meta-data
